/**
 * Build script: 扫描 public/pc 和 public/mp 目录，
 * 生成 api/_manifest.js 供 Serverless Function 使用
 */
const fs = require('fs');
const path = require('path');

const CATEGORIES = ['pc', 'mp'];
const IMAGE_REGEX = /\.(webp|jpg|jpeg|png|gif)$/i;

const manifest = {};

for (const cat of CATEGORIES) {
  const dir = path.join(__dirname, '..', 'public', cat);
  try {
    const files = fs.readdirSync(dir).filter(f => IMAGE_REGEX.test(f));
    manifest[cat] = files;
    console.log(`✅ ${cat}: found ${files.length} images`);
  } catch (err) {
    console.error(`❌ Failed to read ${cat}: ${err.message}`);
    manifest[cat] = [];
  }
}

const output = `// Auto-generated by scripts/build.js — DO NOT EDIT
module.exports = ${JSON.stringify(manifest, null, 2)};
`;

const outPath = path.join(__dirname, '..', 'api', '_manifest.js');
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`\n✅ Manifest written to api/_manifest.js`);
